theme:slate
title:"Too little for a paper"
description: "There are some of my research notes (mainly technical) that are too insignificant for a paper but significant enough to be useful to other astronomers."

